//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holt.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerImpl
    {
        public CustomerImpl()
        {
            this.Jobs = new HashSet<JobImpl>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<JobImpl> Jobs { get; set; }
    }
}
