//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holt.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationImpl
    {
        public NotificationImpl()
        {
            this.Groups = new HashSet<GroupImpl>();
            this.Users = new HashSet<UserImpl>();
        }
    
        public string NotificationName { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<GroupImpl> Groups { get; set; }
        public virtual ICollection<UserImpl> Users { get; set; }
    }
}
