//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Holt.DataAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatusImpl
    {
        public UserStatusImpl()
        {
            this.Users = new HashSet<UserImpl>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<UserImpl> Users { get; set; }
    }
}
